**Numpy**

In [196]:
import numpy as np

In [197]:
#scalar 
x=5


In [198]:
#vector 
vector1= np.array([1,2,3,4])
vector1

array([1, 2, 3, 4])

In [199]:
np.array((3,4,5,6))

array([3, 4, 5, 6])

In [200]:
type(vector1)

numpy.ndarray

In [201]:
matrix1=np.array([[4,3,2],[3,2,5]])

In [202]:
matrix1

array([[4, 3, 2],
       [3, 2, 5]])

In [203]:
matrix1.shape

(2, 3)

In [204]:
vector1.shape

(4,)

In [205]:
'''create 2 matrices , the matrices should have the same dimension and call matrix 1 + matrix 2
'''

matrix1=np.array([[1,2,3],[8,4,3]])
matrix2=np.array([[9,9,1],[1,6,3]])

matrix1+matrix2

array([[10, 11,  4],
       [ 9, 10,  6]])

In [206]:
matrix1*matrix2

array([[ 9, 18,  3],
       [ 8, 24,  9]])

In [207]:
matrix1*2

array([[ 2,  4,  6],
       [16,  8,  6]])

In [208]:
m1=np.array([[2,6],[4,8]])
m2=np.array([[4,2],[7,9]])
m1.dot(m2)

array([[50, 58],
       [72, 80]])

In [209]:
m2.dot(m1)

array([[ 16,  40],
       [ 50, 114]])

In [210]:
matrix2=matrix2.reshape(3,2)

In [211]:
matrix1.dot(matrix2)

array([[29, 20],
       [94, 85]])

In [212]:
matrix1[0][0]=3.14
matrix1

array([[3, 2, 3],
       [8, 4, 3]])

In [213]:
np.arange(1,6)

array([1, 2, 3, 4, 5])

In [214]:
arr1=np.arange(1,6,2)

In [215]:
arr1.shape

(3,)

In [216]:
arr1=np.arange(1,26,2)
arr1

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25])

**Pandas**

In [217]:
'''
we have :
        series => a single column table
        data frame => 
        
'''        

'\nwe have :\n        series => a single column table\n        data frame => \n        \n'

In [218]:
import pandas as pd

In [219]:
data= pd.Series([10,20,30])

In [220]:
data

0    10
1    20
2    30
dtype: int64

In [221]:
type(data)

pandas.core.series.Series

In [222]:
data2=pd.Series(["a","b","c"])
type(data2)

pandas.core.series.Series

In [223]:
print(data.sum())

60


In [224]:
data.max()

30

In [225]:
data.idxmax()

2

In [226]:
data.idxmin()

0

In [227]:
v1=np.array([1,2,3,4])

In [228]:
d=pd.Series(v1)

In [229]:
d
d.dtype

dtype('int32')

In [230]:
pd.DataFrame({"user":"Tushar","marks":100},index=[0])

user  marks
0  Tushar    100

In [231]:
pd.DataFrame({"user":["Tushar","Lokesh"],"marks":100})

user  marks
0  Tushar    100
1  Lokesh    100

In [232]:
#row lable index => givrn by the user

In [233]:
import collections
# Create a deque
DoubleEnded = collections.deque(["Mon","Tue","Wed"])
print (DoubleEnded)

# Append to the right
print("Adding to the right: ")
DoubleEnded.append("Thu")
print (DoubleEnded)

# append to the left
print("Adding to the left: ")
DoubleEnded.appendleft("Sun")
print (DoubleEnded)

# Remove from the right
print("Removing from the right: ")
DoubleEnded.pop()
print (DoubleEnded)

# Remove from the left
print("Removing from the left: ")
DoubleEnded.popleft()
print (DoubleEnded)

# Reverse the dequeue
print("Reversing the deque: ")
DoubleEnded.reverse()
print (DoubleEnded)

deque(['Mon', 'Tue', 'Wed'])
Adding to the right: 
deque(['Mon', 'Tue', 'Wed', 'Thu'])
Adding to the left: 
deque(['Sun', 'Mon', 'Tue', 'Wed', 'Thu'])
Removing from the right: 
deque(['Sun', 'Mon', 'Tue', 'Wed'])
Removing from the left: 
deque(['Mon', 'Tue', 'Wed'])
Reversing the deque: 
deque(['Wed', 'Tue', 'Mon'])


In [234]:
import pandas as pd
pk=pd.read_csv("pokemon_data.csv")

In [235]:
df=pd.read_csv("NbaInfo.csv")
collegeseries=df["College"]

'''create a function ion case the college name start with T ,M B then we have to print invitation accepted else not accepted'''

collegeseries=collegeseries.dropna

In [236]:
def func(val):

    if val[0] in "MTBmtb":
        return( f" {val} -invitation accepted")
    else:
        return( f" {val} invitation not accepted")

# collegeseries.apply(func)


In [237]:
collegeseries.describe()

AttributeError: 'function' object has no attribute 'describe'

In [238]:
df[["Name","Salary","College"]]

Name     Salary            College
0    Avery Bradley  7730337.0              Texas
1      Jae Crowder  6796117.0          Marquette
2     John Holland        NaN  Boston University
3      R.J. Hunter  1148640.0      Georgia State
4    Jonas Jerebko  5000000.0                NaN
..             ...        ...                ...
453   Shelvin Mack  2433333.0             Butler
454      Raul Neto   900000.0                NaN
455   Tibor Pleiss  2900000.0                NaN
456    Jeff Withey   947276.0             Kansas
457            NaN        NaN                NaN

[458 rows x 3 columns]

In [239]:

collegeseries.nunique()

AttributeError: 'function' object has no attribute 'nunique'

In [240]:
df

Name            Team  Number Position   Age Height  Weight  \
0    Avery Bradley  Boston Celtics     0.0       PG  25.0    6-2   180.0   
1      Jae Crowder  Boston Celtics    99.0       SF  25.0    6-6   235.0   
2     John Holland  Boston Celtics    30.0       SG  27.0    6-5   205.0   
3      R.J. Hunter  Boston Celtics    28.0       SG  22.0    6-5   185.0   
4    Jonas Jerebko  Boston Celtics     8.0       PF  29.0   6-10   231.0   
..             ...             ...     ...      ...   ...    ...     ...   
453   Shelvin Mack       Utah Jazz     8.0       PG  26.0    6-3   203.0   
454      Raul Neto       Utah Jazz    25.0       PG  24.0    6-1   179.0   
455   Tibor Pleiss       Utah Jazz    21.0        C  26.0    7-3   256.0   
456    Jeff Withey       Utah Jazz    24.0        C  26.0    7-0   231.0   
457            NaN             NaN     NaN      NaN   NaN    NaN     NaN   

               College     Salary  
0                Texas  7730337.0  
1            Marquette  6796117.0  
2    Boston University        NaN  
3        Georgia State  1148640.0  
4                  NaN  5000000.0  
..                 ...        ...  
453             Butler  2433333.0  
454                NaN   900000.0  
455                NaN  2900000.0  
456             Kansas   947276.0  
457                NaN        NaN  

[458 rows x 9 columns]

In [241]:
collegeseries.describe()

AttributeError: 'function' object has no attribute 'describe'

In [242]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 458 entries, 0 to 457
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Name      457 non-null    object 
 1   Team      457 non-null    object 
 2   Number    457 non-null    float64
 3   Position  457 non-null    object 
 4   Age       457 non-null    float64
 5   Height    457 non-null    object 
 6   Weight    457 non-null    float64
 7   College   373 non-null    object 
 8   Salary    446 non-null    float64
dtypes: float64(4), object(5)
memory usage: 32.3+ KB


In [243]:
d=df.dropna(axis=0)
d

Name            Team  Number Position   Age Height  Weight  \
0    Avery Bradley  Boston Celtics     0.0       PG  25.0    6-2   180.0   
1      Jae Crowder  Boston Celtics    99.0       SF  25.0    6-6   235.0   
3      R.J. Hunter  Boston Celtics    28.0       SG  22.0    6-5   185.0   
6    Jordan Mickey  Boston Celtics    55.0       PF  21.0    6-8   235.0   
7     Kelly Olynyk  Boston Celtics    41.0        C  25.0    7-0   238.0   
..             ...             ...     ...      ...   ...    ...     ...   
449    Rodney Hood       Utah Jazz     5.0       SG  23.0    6-8   206.0   
451  Chris Johnson       Utah Jazz    23.0       SF  26.0    6-6   206.0   
452     Trey Lyles       Utah Jazz    41.0       PF  20.0   6-10   234.0   
453   Shelvin Mack       Utah Jazz     8.0       PG  26.0    6-3   203.0   
456    Jeff Withey       Utah Jazz    24.0        C  26.0    7-0   231.0   

           College     Salary  
0            Texas  7730337.0  
1        Marquette  6796117.0  
3    Georgia State  1148640.0  
6              LSU  1170960.0  
7          Gonzaga  2165160.0  
..             ...        ...  
449           Duke  1348440.0  
451         Dayton   981348.0  
452       Kentucky  2239800.0  
453         Butler  2433333.0  
456         Kansas   947276.0  

[364 rows x 9 columns]

In [244]:
d.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 364 entries, 0 to 456
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Name      364 non-null    object 
 1   Team      364 non-null    object 
 2   Number    364 non-null    float64
 3   Position  364 non-null    object 
 4   Age       364 non-null    float64
 5   Height    364 non-null    object 
 6   Weight    364 non-null    float64
 7   College   364 non-null    object 
 8   Salary    364 non-null    float64
dtypes: float64(4), object(5)
memory usage: 28.4+ KB


In [245]:
print(d)

              Name            Team  Number Position   Age Height  Weight  \
0    Avery Bradley  Boston Celtics     0.0       PG  25.0    6-2   180.0   
1      Jae Crowder  Boston Celtics    99.0       SF  25.0    6-6   235.0   
3      R.J. Hunter  Boston Celtics    28.0       SG  22.0    6-5   185.0   
6    Jordan Mickey  Boston Celtics    55.0       PF  21.0    6-8   235.0   
7     Kelly Olynyk  Boston Celtics    41.0        C  25.0    7-0   238.0   
..             ...             ...     ...      ...   ...    ...     ...   
449    Rodney Hood       Utah Jazz     5.0       SG  23.0    6-8   206.0   
451  Chris Johnson       Utah Jazz    23.0       SF  26.0    6-6   206.0   
452     Trey Lyles       Utah Jazz    41.0       PF  20.0   6-10   234.0   
453   Shelvin Mack       Utah Jazz     8.0       PG  26.0    6-3   203.0   
456    Jeff Withey       Utah Jazz    24.0        C  26.0    7-0   231.0   

           College     Salary  
0            Texas  7730337.0  
1        Marquette  679

In [246]:
df.dropna(subset=["Salary","College"])

Name            Team  Number Position   Age Height  Weight  \
0    Avery Bradley  Boston Celtics     0.0       PG  25.0    6-2   180.0   
1      Jae Crowder  Boston Celtics    99.0       SF  25.0    6-6   235.0   
3      R.J. Hunter  Boston Celtics    28.0       SG  22.0    6-5   185.0   
6    Jordan Mickey  Boston Celtics    55.0       PF  21.0    6-8   235.0   
7     Kelly Olynyk  Boston Celtics    41.0        C  25.0    7-0   238.0   
..             ...             ...     ...      ...   ...    ...     ...   
449    Rodney Hood       Utah Jazz     5.0       SG  23.0    6-8   206.0   
451  Chris Johnson       Utah Jazz    23.0       SF  26.0    6-6   206.0   
452     Trey Lyles       Utah Jazz    41.0       PF  20.0   6-10   234.0   
453   Shelvin Mack       Utah Jazz     8.0       PG  26.0    6-3   203.0   
456    Jeff Withey       Utah Jazz    24.0        C  26.0    7-0   231.0   

           College     Salary  
0            Texas  7730337.0  
1        Marquette  6796117.0  
3    Georgia State  1148640.0  
6              LSU  1170960.0  
7          Gonzaga  2165160.0  
..             ...        ...  
449           Duke  1348440.0  
451         Dayton   981348.0  
452       Kentucky  2239800.0  
453         Butler  2433333.0  
456         Kansas   947276.0  

[364 rows x 9 columns]

In [247]:

df = df.dropna()[["Salary","Age","Weight"]].astype("int")

In [248]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 364 entries, 0 to 456
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Salary  364 non-null    int32
 1   Age     364 non-null    int32
 2   Weight  364 non-null    int32
dtypes: int32(3)
memory usage: 7.1 KB


In [249]:
df.fillna(0)

Salary  Age  Weight
0    7730337   25     180
1    6796117   25     235
3    1148640   22     185
6    1170960   21     235
7    2165160   25     238
..       ...  ...     ...
449  1348440   23     206
451   981348   26     206
452  2239800   20     234
453  2433333   26     203
456   947276   26     231

[364 rows x 3 columns]

In [250]:
df=pd.read_csv("NbaInfo.csv")


In [251]:
df[["Salary"]]=df[["Salary"]].fillna(0)

In [252]:
df[["College","Name","Team"]]=df[["College","Name","Team"]].fillna("unknown")
df

Name            Team  Number Position   Age Height  Weight  \
0    Avery Bradley  Boston Celtics     0.0       PG  25.0    6-2   180.0   
1      Jae Crowder  Boston Celtics    99.0       SF  25.0    6-6   235.0   
2     John Holland  Boston Celtics    30.0       SG  27.0    6-5   205.0   
3      R.J. Hunter  Boston Celtics    28.0       SG  22.0    6-5   185.0   
4    Jonas Jerebko  Boston Celtics     8.0       PF  29.0   6-10   231.0   
..             ...             ...     ...      ...   ...    ...     ...   
453   Shelvin Mack       Utah Jazz     8.0       PG  26.0    6-3   203.0   
454      Raul Neto       Utah Jazz    25.0       PG  24.0    6-1   179.0   
455   Tibor Pleiss       Utah Jazz    21.0        C  26.0    7-3   256.0   
456    Jeff Withey       Utah Jazz    24.0        C  26.0    7-0   231.0   
457        unknown         unknown     NaN      NaN   NaN    NaN     NaN   

               College     Salary  
0                Texas  7730337.0  
1            Marquette  6796117.0  
2    Boston University        0.0  
3        Georgia State  1148640.0  
4              unknown  5000000.0  
..                 ...        ...  
453             Butler  2433333.0  
454            unknown   900000.0  
455            unknown  2900000.0  
456             Kansas   947276.0  
457            unknown        0.0  

[458 rows x 9 columns]

In [253]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 458 entries, 0 to 457
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Name      458 non-null    object 
 1   Team      458 non-null    object 
 2   Number    457 non-null    float64
 3   Position  457 non-null    object 
 4   Age       457 non-null    float64
 5   Height    457 non-null    object 
 6   Weight    457 non-null    float64
 7   College   458 non-null    object 
 8   Salary    458 non-null    float64
dtypes: float64(4), object(5)
memory usage: 32.3+ KB


In [254]:
df["Salary"].astype("category")

C:\Users\futurense.MILE-BL-4171-LA\anaconda3\lib\site-packages\IPython\lib\pretty.py:700: FutureWarning: Index.ravel returning ndarray is deprecated; in a future version this will return a view on self.
  output = repr(obj)


0      7730337.0
1      6796117.0
2            0.0
3      1148640.0
4      5000000.0
         ...    
453    2433333.0
454     900000.0
455    2900000.0
456     947276.0
457          0.0
Name: Salary, Length: 458, dtype: category
Categories (310, float64): [0.0, 30888.0, 55722.0, 83397.0, ..., 22359364.0, 22875000.0, 22970500.0, 25000000.0]

In [255]:
df.sort_values(by=["Team","Salary"],ascending=False)

Name                Team  Number Position   Age Height  \
457           unknown             unknown     NaN      NaN   NaN    NaN   
382         John Wall  Washington Wizards     2.0       PG  25.0    6-4   
375      Nene Hilario  Washington Wizards    42.0        C  33.0   6-11   
373     Marcin Gortat  Washington Wizards    13.0        C  32.0   6-11   
376   Markieff Morris  Washington Wizards     5.0       PF  26.0   6-10   
..                ...                 ...     ...      ...   ...    ...   
310  Tim Hardaway Jr.       Atlanta Hawks    10.0       SG  24.0    6-6   
313    Kris Humphries       Atlanta Hawks    43.0       PF  31.0    6-9   
322    Walter Tavares       Atlanta Hawks    22.0        C  24.0    7-3   
316      Mike Muscala       Atlanta Hawks    31.0       PF  24.0   6-11   
317   Lamar Patterson       Atlanta Hawks    13.0       SG  24.0    6-5   

     Weight     College      Salary  
457     NaN     unknown         0.0  
382   195.0    Kentucky  15851950.0  
375   250.0     unknown  13000000.0  
373   240.0     unknown  11217391.0  
376   245.0      Kansas   8000000.0  
..      ...         ...         ...  
310   205.0    Michigan   1304520.0  
313   235.0   Minnesota   1000000.0  
322   260.0     unknown   1000000.0  
316   240.0    Bucknell    947276.0  
317   225.0  Pittsburgh    525093.0  

[458 rows x 9 columns]

In [256]:
s1=df["Team"]
s1.=(len)

SyntaxError: invalid syntax (651422926.py, line 2)

In [257]:
df.dropna(inplace=True)

In [258]:
df.sort_values(by=["Team"],ascending=False,inplace=True)

In [259]:
df[df.duplicated(subset=["Team"],keep="first")]

Name                Team  Number Position   Age Height  \
368     Alan Anderson  Washington Wizards     6.0       SG  33.0    6-6   
382         John Wall  Washington Wizards     2.0       PG  25.0    6-4   
381   Marcus Thornton  Washington Wizards    15.0       SF  29.0    6-4   
380    Garrett Temple  Washington Wizards    17.0       SG  30.0    6-6   
379    Ramon Sessions  Washington Wizards     7.0       PG  30.0    6-3   
..                ...                 ...     ...      ...   ...    ...   
314       Kyle Korver       Atlanta Hawks    26.0       SG  35.0    6-7   
313    Kris Humphries       Atlanta Hawks    43.0       PF  31.0    6-9   
312        Al Horford       Atlanta Hawks    15.0        C  30.0   6-10   
311      Kirk Hinrich       Atlanta Hawks    12.0       SG  35.0    6-4   
310  Tim Hardaway Jr.       Atlanta Hawks    10.0       SG  24.0    6-6   

     Weight         College      Salary  
368   220.0  Michigan State   4000000.0  
382   195.0        Kentucky  15851950.0  
381   205.0             LSU    200600.0  
380   195.0             LSU   1100602.0  
379   190.0          Nevada   2170465.0  
..      ...             ...         ...  
314   212.0       Creighton   5746479.0  
313   235.0       Minnesota   1000000.0  
312   245.0         Florida  12000000.0  
311   190.0          Kansas   2854940.0  
310   205.0        Michigan   1304520.0  

[427 rows x 9 columns]

In [260]:
df[df.duplicated(subset=["Team"],keep=False)]

Name                Team  Number Position   Age Height  \
370      Jared Dudley  Washington Wizards     1.0       SF  30.0    6-7   
368     Alan Anderson  Washington Wizards     6.0       SG  33.0    6-6   
382         John Wall  Washington Wizards     2.0       PG  25.0    6-4   
381   Marcus Thornton  Washington Wizards    15.0       SF  29.0    6-4   
380    Garrett Temple  Washington Wizards    17.0       SG  30.0    6-6   
..                ...                 ...     ...      ...   ...    ...   
314       Kyle Korver       Atlanta Hawks    26.0       SG  35.0    6-7   
313    Kris Humphries       Atlanta Hawks    43.0       PF  31.0    6-9   
312        Al Horford       Atlanta Hawks    15.0        C  30.0   6-10   
311      Kirk Hinrich       Atlanta Hawks    12.0       SG  35.0    6-4   
310  Tim Hardaway Jr.       Atlanta Hawks    10.0       SG  24.0    6-6   

     Weight         College      Salary  
370   225.0  Boston College   4375000.0  
368   220.0  Michigan State   4000000.0  
382   195.0        Kentucky  15851950.0  
381   205.0             LSU    200600.0  
380   195.0             LSU   1100602.0  
..      ...             ...         ...  
314   212.0       Creighton   5746479.0  
313   235.0       Minnesota   1000000.0  
312   245.0         Florida  12000000.0  
311   190.0          Kansas   2854940.0  
310   205.0        Michigan   1304520.0  

[457 rows x 9 columns]

In [261]:
df[~df.duplicated(subset=["Team"],keep="first")]

Name                    Team  Number Position   Age Height  \
370        Jared Dudley      Washington Wizards     1.0       SF  30.0    6-7   
456         Jeff Withey               Utah Jazz    24.0        C  26.0    7-0   
62        Bruno Caboclo         Toronto Raptors    20.0       SF  20.0    6-9   
307    Jonathon Simmons       San Antonio Spurs    17.0       SG  26.0    6-6   
139        Caron Butler        Sacramento Kings    31.0       SF  36.0    6-7   
427     Cliff Alexander  Portland Trail Blazers    34.0       PF  20.0    6-8   
127      Brandon Knight            Phoenix Suns     3.0       PG  24.0    6-3   
49          Joel Embiid      Philadelphia 76ers    21.0        C  22.0    7-0   
357       Mario Hezonja           Orlando Magic    23.0       SG  21.0    6-8   
422       Cameron Payne   Oklahoma City Thunder    22.0       PG  21.0    6-3   
40   Kristaps Porzingis         New York Knicks     6.0       PF  20.0    7-3   
280    Dante Cunningham    New Orleans Pelicans    44.0       PF  29.0    6-8   
402         Zach LaVine  Minnesota Timberwolves     8.0       PG  21.0    6-5   
215         Tyler Ennis         Milwaukee Bucks    11.0       PG  21.0    6-3   
351    Hassan Whiteside              Miami Heat    21.0        C  26.0    7-0   
261        Vince Carter       Memphis Grizzlies    15.0       SG  39.0    6-6   
114     Larry Nance Jr.      Los Angeles Lakers     7.0       PF  23.0    6-9   
100          Chris Paul    Los Angeles Clippers     3.0       PG  31.0    6-0   
207      Rodney Stuckey          Indiana Pacers     2.0       PG  30.0    6-5   
248    Andrew Goudelock         Houston Rockets     0.0       PG  27.0    6-3   
81         Festus Ezeli   Golden State Warriors    31.0        C  26.0   6-11   
195    Anthony Tolliver         Detroit Pistons    43.0       PF  31.0    6-8   
396      JaKarr Sampson          Denver Nuggets     9.0       SG  23.0    6-9   
228          J.J. Barea        Dallas Mavericks     5.0       PG  31.0    6-0   
180         Mo Williams     Cleveland Cavaliers    52.0       PG  33.0    6-1   
151    Cameron Bairstow           Chicago Bulls    41.0       PF  25.0    6-9   
337     Marvin Williams       Charlotte Hornets     2.0       PF  29.0    6-9   
28         Donald Sloan           Brooklyn Nets    15.0       PG  28.0    6-3   
14         Tyler Zeller          Boston Celtics    44.0        C  26.0    7-0   
309       Kent Bazemore           Atlanta Hawks    24.0       SF  26.0    6-5   

     Weight             College      Salary  
370   225.0      Boston College   4375000.0  
456   231.0              Kansas    947276.0  
62    205.0             unknown   1524000.0  
307   195.0             Houston    525093.0  
139   228.0         Connecticut   1449187.0  
427   240.0              Kansas    525093.0  
127   189.0            Kentucky  13500000.0  
49    250.0              Kansas   4626960.0  
357   218.0             unknown   3741480.0  
422   185.0        Murray State   2021520.0  
40    240.0             unknown   4131720.0  
280   230.0           Villanova   2850000.0  
402   189.0                UCLA   2148360.0  
215   194.0            Syracuse   1662360.0  
351   265.0            Marshall    981348.0  
261   220.0      North Carolina   4088019.0  
114   230.0             Wyoming   1155600.0  
100   175.0         Wake Forest  21468695.0  
207   205.0  Eastern Washington   7000000.0  
248   200.0          Charleston    200600.0  
81    265.0          Vanderbilt   2008748.0  
195   240.0           Creighton   3000000.0  
396   214.0          St. John's    258489.0  
228   185.0        Northeastern   4290000.0  
180   198.0             Alabama   2100000.0  
151   250.0          New Mexico    845059.0  
337   237.0      North Carolina   7000000.0  
28    205.0           Texas A&M    947276.0  
14    253.0      North Carolina   2616975.0  
309   201.0        Old Dominion   2000000.0

In [287]:
df

Name                Team  Number Position   Age Height  \
370      Jared Dudley  Washington Wizards     1.0       SF  30.0    6-7   
368     Alan Anderson  Washington Wizards     6.0       SG  33.0    6-6   
382         John Wall  Washington Wizards     2.0       PG  25.0    6-4   
381   Marcus Thornton  Washington Wizards    15.0       SF  29.0    6-4   
380    Garrett Temple  Washington Wizards    17.0       SG  30.0    6-6   
..                ...                 ...     ...      ...   ...    ...   
314       Kyle Korver       Atlanta Hawks    26.0       SG  35.0    6-7   
313    Kris Humphries       Atlanta Hawks    43.0       PF  31.0    6-9   
312        Al Horford       Atlanta Hawks    15.0        C  30.0   6-10   
311      Kirk Hinrich       Atlanta Hawks    12.0       SG  35.0    6-4   
310  Tim Hardaway Jr.       Atlanta Hawks    10.0       SG  24.0    6-6   

     Weight         College      Salary  
370   225.0  Boston College   4375000.0  
368   220.0  Michigan State   4000000.0  
382   195.0        Kentucky  15851950.0  
381   205.0             LSU    200600.0  
380   195.0             LSU   1100602.0  
..      ...             ...         ...  
314   212.0       Creighton   5746479.0  
313   235.0       Minnesota   1000000.0  
312   245.0         Florida  12000000.0  
311   190.0          Kansas   2854940.0  
310   205.0        Michigan   1304520.0  

[457 rows x 9 columns]

In [288]:
arr1=np.array([[2,3,4],[4,5,6]])


# 

In [263]:
arr1

array([[2, 3, 4],
       [4, 5, 6]])

In [264]:
arr1.shape

(2, 3)

In [265]:
arr1[0]

array([2, 3, 4])

In [267]:
arr1[0][1]=99

# 

In [268]:
arr1

array([[ 2, 99,  4],
       [ 4,  5,  6]])

In [269]:
arr1+12


array([[ 14, 111,  16],
       [ 16,  17,  18]])

In [281]:
arr2=np.array([[ 14, 111,  16],[ 16,  17,  18],[1,2,3]])

In [282]:
arr3=np.array([1,2,3])

In [286]:
arr3+arr1

array([[  3, 101,   7],
       [  5,   7,   9]])

In [285]:
np.add(arr1,arr3)

array([[  3, 101,   7],
       [  5,   7,   9]])

In [ ]:
'''
when we are performing slicing operation on array , what type of output we will get
'''

In [300]:
df=df.dropna()
c1=df["Salary"].between (400000 ,2800000)
df[c1]

Name                Team  Number Position   Age Height  \
380    Garrett Temple  Washington Wizards    17.0       SG  30.0    6-6   
379    Ramon Sessions  Washington Wizards     7.0       PG  30.0    6-3   
377   Kelly Oubre Jr.  Washington Wizards    12.0       SF  20.0    6-7   
371      Jarell Eddie  Washington Wizards     8.0       SG  24.0    6-7   
456       Jeff Withey           Utah Jazz    24.0        C  26.0    7-0   
..                ...                 ...     ...      ...   ...    ...   
318   Dennis Schroder       Atlanta Hawks    17.0       PG  22.0    6-1   
317   Lamar Patterson       Atlanta Hawks    13.0       SG  24.0    6-5   
316      Mike Muscala       Atlanta Hawks    31.0       PF  24.0   6-11   
313    Kris Humphries       Atlanta Hawks    43.0       PF  31.0    6-9   
310  Tim Hardaway Jr.       Atlanta Hawks    10.0       SG  24.0    6-6   

     Weight        College     Salary  
380   195.0            LSU  1100602.0  
379   190.0         Nevada  2170465.0  
377   205.0         Kansas  1920240.0  
371   218.0  Virginia Tech   561716.0  
456   231.0         Kansas   947276.0  
..      ...            ...        ...  
318   172.0        unknown  1763400.0  
317   225.0     Pittsburgh   525093.0  
316   240.0       Bucknell   947276.0  
313   235.0      Minnesota  1000000.0  
310   205.0       Michigan  1304520.0  

[193 rows x 9 columns]

In [306]:
c2=df["Age"].isin (range(25,28))

In [308]:
df[c2 & c1]

Name                    Team  Number Position   Age  \
456          Jeff Withey               Utah Jazz    24.0        C  26.0   
451        Chris Johnson               Utah Jazz    23.0       SF  26.0   
453         Shelvin Mack               Utah Jazz     8.0       PG  26.0   
307     Jonathon Simmons       San Antonio Spurs    17.0       SG  26.0   
302     Boban Marjanovic       San Antonio Spurs    40.0        C  27.0   
144           Seth Curry        Sacramento Kings    30.0       SG  25.0   
136           Quincy Acy        Sacramento Kings    13.0       SF  25.0   
137       James Anderson        Sacramento Kings     5.0       SG  27.0   
439        Mason Plumlee  Portland Trail Blazers    24.0        C  26.0   
129            Jon Leuer            Phoenix Suns    30.0       PF  27.0   
126         John Jenkins            Phoenix Suns    23.0       SG  25.0   
59       Hollis Thompson      Philadelphia 76ers    31.0       SG  25.0   
57             Ish Smith      Philadelphia 76ers     1.0       PG  27.0   
47         Isaiah Canaan      Philadelphia 76ers     0.0       PG  25.0   
48      Robert Covington      Philadelphia 76ers    33.0       SF  25.0   
354       Dewayne Dedmon           Orlando Magic     3.0        C  26.0   
362     Andrew Nicholson           Orlando Magic    44.0       PF  26.0   
35      Cleanthony Early         New York Knicks    11.0       SF  25.0   
278         Luke Babbitt    New Orleans Pelicans     8.0       SF  26.0   
284          James Ennis    New Orleans Pelicans     4.0       SF  25.0   
286          Tim Frazier    New Orleans Pelicans     2.0       PG  25.0   
289      Jordan Hamilton    New Orleans Pelicans    25.0       SG  25.0   
399         Gorgui Dieng  Minnesota Timberwolves     5.0        C  26.0   
404        Adreian Payne  Minnesota Timberwolves    33.0       PF  25.0   
214     Jared Cunningham         Milwaukee Bucks     9.0       SG  25.0   
224        Miles Plumlee         Milwaukee Bucks    18.0        C  27.0   
351     Hassan Whiteside              Miami Heat    21.0        C  26.0   
266       JaMychal Green       Memphis Grizzlies     0.0       PF  25.0   
117         Robert Sacre      Los Angeles Lakers    50.0        C  27.0   
113           Ryan Kelly      Los Angeles Lakers     4.0       PF  25.0   
91          Cole Aldrich    Los Angeles Clippers    45.0        C  27.0   
105          C.J. Wilcox    Los Angeles Clippers    30.0       SG  25.0   
202         Solomon Hill          Indiana Pacers    44.0       SF  25.0   
209   Shayne Whittington          Indiana Pacers    42.0       PF  25.0   
254   Donatas Motiejunas         Houston Rockets    20.0       PF  25.0   
81          Festus Ezeli   Golden State Warriors    31.0        C  26.0   
79             Ian Clark   Golden State Warriors    21.0       SG  25.0   
185       Reggie Bullock         Detroit Pistons    25.0       SF  25.0   
166  Matthew Dellavedova     Cleveland Cavaliers     8.0       PG  25.0   
151     Cameron Bairstow           Chicago Bulls    41.0       PF  25.0   
158       Justin Holiday           Chicago Bulls     7.0       SG  27.0   
161        E'Twaun Moore           Chicago Bulls    55.0       SG  27.0   
335           Jeremy Lin       Charlotte Hornets     7.0       PG  27.0   
27            Henry Sims           Brooklyn Nets    14.0        C  26.0   
26       Thomas Robinson           Brooklyn Nets    41.0       PF  25.0   
25           Willie Reed           Brooklyn Nets    33.0       PF  26.0   
14          Tyler Zeller          Boston Celtics    44.0        C  26.0   
7           Kelly Olynyk          Boston Celtics    41.0        C  25.0   
309        Kent Bazemore           Atlanta Hawks    24.0       SF  26.0   

    Height  Weight           College     Salary  
456    7-0   231.0            Kansas   947276.0  
451    6-6   206.0            Dayton   981348.0  
453    6-3   203.0            Butler  2433333.0  
307    6-6   195.0           Houston   525093.0  
302    7-3   290.0 

In [309]:
c2=df["Team"].i ("Boston Celtics")

TypeError: only list-like objects are allowed to be passed to isin(), you passed a [str]

In [316]:
c2=df["Team"].isin(["Portland Trail Blaizer","Boston Celtics"])

c3=df["Salary"]>3500000

In [321]:
df[c2|c3]

Name                Team  Number Position   Age Height  \
370     Jared Dudley  Washington Wizards     1.0       SF  30.0    6-7   
368    Alan Anderson  Washington Wizards     6.0       SG  33.0    6-6   
382        John Wall  Washington Wizards     2.0       PG  25.0    6-4   
378  Otto Porter Jr.  Washington Wizards    22.0       SF  23.0    6-8   
376  Markieff Morris  Washington Wizards     5.0       PF  26.0   6-10   
..               ...                 ...     ...      ...   ...    ...   
321   Tiago Splitter       Atlanta Hawks    11.0        C  31.0   6-11   
320  Thabo Sefolosha       Atlanta Hawks    25.0       SF  32.0    6-7   
315     Paul Millsap       Atlanta Hawks     4.0       PF  31.0    6-8   
314      Kyle Korver       Atlanta Hawks    26.0       SG  35.0    6-7   
312       Al Horford       Atlanta Hawks    15.0        C  30.0   6-10   

     Weight         College      Salary  
370   225.0  Boston College   4375000.0  
368   220.0  Michigan State   4000000.0  
382   195.0        Kentucky  15851950.0  
378   198.0      Georgetown   4662960.0  
376   245.0          Kansas   8000000.0  
..      ...             ...         ...  
321   245.0         unknown   9756250.0  
320   220.0         unknown   4000000.0  
315   246.0  Louisiana Tech  18671659.0  
314   212.0       Creighton   5746479.0  
312   245.0         Florida  12000000.0  

[198 rows x 9 columns]

In [ ]:
#loc and iloc