**Numpy**

In [ ]:
import numpy as np

In [ ]:
#scalar 
x=5


In [ ]:
#vector 
vector1= np.array([1,2,3,4])
vector1

array([1, 2, 3, 4])

In [ ]:
np.array((3,4,5,6))

array([3, 4, 5, 6])

In [ ]:
type(vector1)

numpy.ndarray

In [ ]:
matrix1=np.array([[4,3,2],[3,2,5]])

In [ ]:
matrix1

array([[4, 3, 2],
       [3, 2, 5]])

In [ ]:
matrix1.shape

(2, 3)

In [ ]:
vector1.shape

(4,)

In [ ]:
'''create 2 matrices , the matrices should have the same dimension and call matrix 1 + matrix 2
'''

matrix1=np.array([[1,2,3],[8,4,3]])
matrix2=np.array([[9,9,1],[1,6,3]])

matrix1+matrix2

array([[10, 11,  4],
       [ 9, 10,  6]])

In [ ]:
matrix1*matrix2

array([[ 9, 18,  3],
       [ 8, 24,  9]])

In [ ]:
matrix1*2

array([[ 2,  4,  6],
       [16,  8,  6]])

In [ ]:
m1=np.array([[2,6],[4,8]])
m2=np.array([[4,2],[7,9]])
m1.dot(m2)

array([[50, 58],
       [72, 80]])

In [ ]:
m2.dot(m1)

array([[ 16,  40],
       [ 50, 114]])

In [ ]:
matrix2=matrix2.reshape(3,2)

In [ ]:
matrix1.dot(matrix2)

array([[29, 20],
       [94, 85]])

In [ ]:
matrix1[0][0]=3.14
matrix1

array([[3, 2, 3],
       [8, 4, 3]])

In [ ]:
np.arange(1,6)

array([1, 2, 3, 4, 5])

In [ ]:
arr1=np.arange(1,6,2)

In [ ]:
arr1.shape

(3,)

In [ ]:
arr1=np.arange(1,26,2)
arr1

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25])

**Pandas**

In [ ]:
'''
we have :
        series => a single column table
        data frame => 
        
'''        

In [ ]:
import pandas as pd

In [ ]:
data= pd.Series([10,20,30])

In [ ]:
data

0    10
1    20
2    30
dtype: int64

In [ ]:
type(data)

pandas.core.series.Series

In [ ]:
data2=pd.Series(["a","b","c"])
type(data2)

pandas.core.series.Series

In [ ]:
print(data.sum())

60


In [ ]:
data.max()

30

In [ ]:
data.idxmax()

2

In [ ]:
data.idxmin()

0

In [ ]:
v1=np.array([1,2,3,4])

In [ ]:
d=pd.Series(v1)

In [ ]:
d
d.dtype

dtype('int64')

In [ ]:
pd.DataFrame({"user":"Tushar","marks":100},index=[0])

user  marks
0  Tushar    100

In [ ]:
pd.DataFrame({"user":["Tushar","Lokesh"],"marks":100})

user  marks
0  Tushar    100
1  Lokesh    100

In [ ]:
#row lable index => givrn by the user

In [ ]:
import collections
# Create a deque
DoubleEnded = collections.deque(["Mon","Tue","Wed"])
print (DoubleEnded)

# Append to the right
print("Adding to the right: ")
DoubleEnded.append("Thu")
print (DoubleEnded)

# append to the left
print("Adding to the left: ")
DoubleEnded.appendleft("Sun")
print (DoubleEnded)

# Remove from the right
print("Removing from the right: ")
DoubleEnded.pop()
print (DoubleEnded)

# Remove from the left
print("Removing from the left: ")
DoubleEnded.popleft()
print (DoubleEnded)

# Reverse the dequeue
print("Reversing the deque: ")
DoubleEnded.reverse()
print (DoubleEnded)

deque(['Mon', 'Tue', 'Wed'])
Adding to the right: 
deque(['Mon', 'Tue', 'Wed', 'Thu'])
Adding to the left: 
deque(['Sun', 'Mon', 'Tue', 'Wed', 'Thu'])
Removing from the right: 
deque(['Sun', 'Mon', 'Tue', 'Wed'])
Removing from the left: 
deque(['Mon', 'Tue', 'Wed'])
Reversing the deque: 
deque(['Wed', 'Tue', 'Mon'])


In [ ]:
import pandas as pd
pokemon=pd.read_csv("pokemo")